name: 打包应用并上传阿里云

# 作用分支
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ master ]
  # schedule:
  #   - cron: '0 2 * * *'
# 任务
jobs:
  deploy:
    # runs-on 指定job任务运行所需要的虚拟机环境（必填）
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.17.1]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - name: executing remote ssh commands using passphrase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          command_timeout: 5m
          script: |
            cd /var/www/game/ && git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/game/server/ && yarn && yarn ci && yarn stop && yarn start
            cd /var/www/game/client/ && yarn && yarn build
